# options: packer_build, dcos_installation, integration_tests, never. Default is dcos_installation. For more details, see README
publish_dcos_images_after: integration_tests
run_framework_tests: false
run_integration_tests: true
tests_to_run:
  - test_packaging.py