# options: packer_build, dcos_installation, integration_tests, never. Default is dcos_installation. For more details, see README
# You can also run custom tests with tests_to_run.
publish_dcos_images_after: integration_tests
run_framework_tests: false
run_integration_tests: true
tests_to_run:
  - -k 'not test_blkio_stats and not test_task_prom_metrics_not_filtered and not test_prom_metrics_containers_app_bridge and not test_dcos_cni_l4lb'
